### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by QuentinRoy** [aMarCruz/rollup-plugin-pug#9]
It seems the installation is broken since last update (0.1.5). Everything works fine with 0.1.4.

Here is the error I receive.

> rollup-plugin-pug@0.1.5 postinstall /Users/quentinroy/Workspace/test/node_modules/rollup-plugin-pug
> node ./build-rt.js
>
> module.js:487
>     throw err;
>     ^
> 
> Error: Cannot find module '/Users/quentinroy/Workspace/test/node_modules/rollup-plugin-pug/build-rt.js'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Function.Module.runMain (module.js:605:10)
>     at startup (bootstrap_node.js:158:16)
>     at bootstrap_node.js:575:3

I am using macOS Sierra, npm 5 and node 8.

**Comment by aMarCruz** [comment]
@all , @QuentinRoy , sorry by that. v0.1.6 is out and working.
